steps:
  install:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm ci
  release:
    image: plugins/docker
    settings:
      repo: lblod/frontend-lokaal-mandatenbeheer
      tags: "${CI_COMMIT_TAG##v}"
      purge: true
    secrets: [docker_username, docker_password]
when:
  event: tag
  ref: refs/tags/v*
